import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import admissionRoutes from './routes/admission.routes.js';
const app = express();
app.use(cors({ origin: process.env.CLIENT_ORIGIN, credentials: true }));
app.use(morgan('dev'));
app.use(express.json());
app.get('/api/health', (_req,res)=>res.json({ok:true}));
app.use('/api/admissions', admissionRoutes);
export default app;
