// client/src/components/termsText.js

export const TERMS_TEXT = `
**Students Agreement Copy - Master Certification Courses with Guaranteed Placement**

**Dear Student,**
**Welcome to Awdiz!** Your Trusted Learning Partner.
**Thanks for choosing us!!**

This agreement has to be agreed upon and signed by all the candidates joining our master programs at Awdiz. This will be a legal affirmation by the candidate that he will follow all the internal rules and regulations put forward by AWDIZ management and will abide by this throughout the duration of the training program.

We make sure the training experience of our students will be comfortable and their journey from a learner to an IT engineer will be memorable at each phase of their personal growth. Our programs quality has been appreciated by many clients who have hired candidates from us and have been associated with us for so many years. Their trust on us is a proof that our candidate learning is on-track.

Our process at Awdiz is simple and focusses basically on the repeated cycle of train - asses- retrain-reassess- till offered. We monitor our students learning at each phase of their course and suggest improvements to make sure the training becomes fruitful to them. We take all the medium of learning into considerations like Online, Classroom, Hybrid and Recorded lectures to make sure student takes maximum advantages of our training inventory and regularly asses them on weekly/monthly and module-based assessments, live projects, and more.

We are currently putting students on to our internal LMS portal which monitors their training attendance, test results, mocks, resume building, internship details, interview opportunities and interview feedbacks till the students successfully comes out with a dream job. Our ultimate goal in monitoring the complete student learning journey is to provide the best practical training to the candidate in the simplest way. When you are monitored, your weaknesses can be converted into strengths and this will lead to an easier gateway for success.

To achieve the above goals and make student focus seriously on their careers, we have put forward certain terms and conditions that will definitely help both students and AWDIZ follow discipline protocols which in turn help students reach their dreams of a high paying IT job. Student has to confirm on the below points and has to follow the same during the complete training program.

 **Terms & Conditions – Master Programs in IT Infrastructure and Software Development**

**Any student failing to fulfil the below criteria’s will not be eligible to attend our placements. This will be a legal re-affirmation from the candidate that he will be serious throughout his training program duration and failing which, AWDIZ will not be or should not be blamed for students not getting jobs.**

• For IT Infra course including Networking, System, Cybersecurity, AWS etc, we are taking admission majorly to male candidates in the age group 21-32 years and Female candidates in the age group 21-25 years only as this industry demands rotational shifts and occasional travel to client place so in both the conditions, should be ready for Company rules and should not decline the offer for travel and shift timings.
• For Software Development courses, we are focusing on candidates under 25 years and has completed a Valid IT degree with good percentage. Recent year Pass-outs are preferred.
• To ensure successful completion of the course, attendance in all classroom or online sessions must exceed 85%. If a session is missed, the student can attend it in another batch by notifying the HR team of Awdiz. Maximum 3 session can be missed and backup is permitted per module beyond which you need to take a special approval from the centre manager or you will not be permitted to attend our placement programs.
• Mandatory 85% Marks in Daily, Weekly and Monthly Assessments, MCQ’s, Assignments, Mock Interviews and Soft Skill training must be successfully completed for student to get into placement process. Failing the above criteria will make the student ineligible for the placement process and such candidates have to take training and mock repetitions, and become eligible again to start their interview process.

• To meet the requirements of the course, required attendance all assignments, quizzes, internships, mock sessions, internal assessments and self-learning activities must be completed in full and before their respective deadlines for each module. Failing on the above terms can make you ineligible for the placement programs.
• Attending all soft skill trainings like English, Aptitude and Personality development sessions are mandatory for candidates. 100% attendance will be recorded and is mandatory. Usually this are conducted on Weekends so that student technical learning should not get effected during normal days.
• Changing batches is generally not permitted, except under certain circumstances such as medical or educational reasons. If approved by the Center Manager, a processing fee of INR 15,000/- will be charged for the batch change and only once throughout the duration of the training.
• Ongoing students are permitted to take a break for a maximum of 15 days, which must be approved in writing by the Center Manager and only in the case of exams, medical emergencies, or other valid, considerate reasons.
• If a candidate takes a break from the course for a period exceeding 7 days without obtaining prior written permission or leave approval that has been approved by the Center Manager, their training admission would be cancelled and no refund would be approved.
• Any act of misconduct, plagiarism, threatening behaviour, harassment, cheating in assessments, use of abusive language, or violation of institute norms and or misuse of AWDIZ resources may result in immediate expulsion from the course without refund.
• Students must adhere to the payment schedule. Delayed or incomplete payments beyond the allowed date may lead to denial of training continuation and access to LMS.
• The course is considered complete when the candidate finishes complete fee payment, finishes all the modules, assignments, assessments, mock sessions and submits the final project assigned by the faculty for each module. Attendance for both technical soft skill trainings will be considered before giving a final go ahead by the Center Manager. Upon completion, a final certificate will be issued and a go ahead would be given for the placement team to initiate the placement services.
• Students scoring above 85% in mocks and have more than 85% attendance will be automatically eligible to for placement services so they will not be considered for training repetition and can be considered for internship, if needed to make them confident.
• Students scoring less than 85% in mocks and / or have less than 85% attendance, who wish to revise or improve their performance, may opt for one-time batch repetition, either:
  - After completing their current training,
  - Or during the ongoing training to revise finished topics and continue pending ones with a new batch,
  - Or start fresh in a new batch altogether.
• Once a candidate completes our master training program and has been approved for Placement services by Center Manager after verification on full fee payment, they become eligible to receive job openings from our side. We take our commitment to students very seriously, and we strive to place our job-ready candidates within 180 days after the go-ahead for placement post successful training completion by the Center Manager.
• In order to be deemed job-ready, a go ahead from Center Manager on student attendance, final training assessments and complete fee payment confirmation would be needed.
• Awdiz cannot be held responsible for any commitments or consequences that arise if the course is delayed by the student for any personal, educational or medical reason, during the course which may result in delays in completing the course or finding a job placement.
• The candidate should be ready to work anywhere in PAN India; they will not be allowed to decline the offer based on location as the criteria. Once offer is declined for any reason, student will be removed from further placement and student has to take readmission in the program by paying the full fees again to start the interview process again. In exceptional cases, we may accept candidates for a particular location but there will be no guarantee that number of interviews for that location would be more. A special approval during admission has to be taken and approved by Center Manager before admission.

• **PDF, PPT’s and Study Materials:** PDFs, PPTs, and required study materials will be shared in digital format after each class or module, enabling students to practice at home.
• If student is opting for Internship before placement or a need may arise by Awdiz placement team to improve technical skill of the candidate, then he must relocate to the location which Awdiz assigns immediately after the training is completed and should be available to start internship immediately. Internship can be Paid or Unpaid so student should not decline the same for any reason.
• We will try our best to schedule all interviews virtually but if for any reason, there is a demand from the client for Face-to-Face (F2F) interview then student needs to be physically present for a minimum of 60 Days for the placement process at the assigned location by Awdiz.
• Candidates are required to attend all interviews arranged by AWDIZ or its authorized placement associates. If a candidate is unable to attend an interview, they must seek approval from the placement manager via email. If a candidate misses two or more interviews arranged by AWDIZ, they will be ineligible to participate in the further placement or interview process.
• The Master programs are 100% Job guarantee package but we do not commit a fixed salary for the candidate but it process so we train the students how to face that question so that our student gets maximum package for that position.
• If the client specifies a fixed duration internship before taking them on their permanent payroll or there is specific duration of employment bond period in the offer letter, the candidate must be open to it, and should be ready to sign a bond agreement as many clients are specific to offer job position to freshers on these conditions. Decline of offer on the basis of both this condition is not permitted.
• Student should accept the offer for direct payrolls and 3rd party payroll for their client locations. They should be comfortable to work for small, medium and large sized companies, banking clients and educational institutions who majorly hire for these resources.
• Based on the course choice by the student, the job guaranteed courses covers many topics to help students get the best opportunities in various IT infrastructure and Development roles and has a training duration between 4.5 – 7 months for different courses which will be briefed to student at the start of the training. We will begin the placement and interview process once students complete some key modules in the course, even if the entire course is not yet completed. Training for the remaining topics will continue alongside the job interviews, so that strong and job-ready candidates do not have to wait long to begin their careers.
• As part of AWDIZ’s Job Guarantee Programs, students are eligible for a wide range of fresher-level roles based on the course they have enrolled in, including but are not limited to Networking, System Administration, Cybersecurity, AWS Cloud, Java Full Stack, and MERN Full Stack. Students may receive job offers under designations mentioned below in the table according to the course enrolled, or other customized job titles used by hiring companies. The exact title may vary depending on the company, but if the core responsibilities align with the skills and technologies taught in the training, the student must accept the offer. Refusal to accept such offers merely based on designation, employer type, or payroll model (direct or third-party) will be considered a violation of the placement policy. In such cases, the student will be disqualified from further placement services unless they re-enrol into the program by paying the full course fee again. AWDIZ reserves the right to validate job role alignment with the training before enforcing this clause.


| Course | Details |
|---|---|
| **Networking and System Expert course** | As covers vast IT topics in various technologies of System, Server and Networking Ticketing Tool Monitoring Tool so student can be placed in different L1 roles like Desktop Support Engineer, IT Support Engineer, Server Administrator, Windows Admin, Server Engineer, NOC, Field Support Engineer, Technical Support Engineer, IT Engineer, Network Engineer, System Admin, IT Field Engineer, Trainee and Network Support Engineer. |
| **Networking, System, and Cybersecurity course** | As this course covers an extensive set of modules including Networking Fundamentals, Windows/Linux Administration, Firewalls, Ticketing Tools, Monitoring Tools, and basic Cybersecurity concepts, students can be placed in multiple fresherlevel IT infrastructure and security-related roles. These roles include, but are not limited to: Network Engineer, System Administrator, IT Support Engineer, Desktop will be in the range of 1.4 Lpa – 6 Lpa. Salary negotiation has to be done by the candidate during their interview Support Engineer, Security Analyst - L1, SOC Analyst - Trainee, NOC Engineer, Windows/Linux Admin, IT Security Support, Technical Support Engineer, Network Support Engineer, Infrastructure Support Executive, Security Operations Intern, Helpdesk Engineer, IT Field Engineer and **Cybersecurity Analyst – Intern**. |
| **Networking, System, and AWS Cloud course** | As this course delivers in-depth training on Networking, Windows/Linux Administration, Server & System Monitoring, Cloud Fundamentals, AWS Services (EC2, S3, IAM, VPC, etc.), and Ticketing Tools, students become eligible for various entry-level roles in IT Infrastructure and Cloud Support. These roles include, but are not limited to: Cloud Support Engineer – L1, AWS Cloud Administrator – Trainee, System Administrator, Network Engineer, Cloud Operations Associate, Infrastructure Support Engineer, Desktop Support Engineer, Server Admin, DevOps Support – Intern, NOC Engineer, Cloud Technical Support, IT Support Engineer, AWS Trainee Engineer and Cloud Helpdesk Engineer. |
| **Full Stack Developer Course** | As this course at AWDIZ covers comprehensive topics across both Java Full Stack (Core Java, JDBC, Spring Boot, REST APIs, MySQL) and MERN Stack (MongoDB, Express.js, React.js, Node.js), along with essential front-end skills (HTML, CSS, JavaScript, Bootstrap) and version control (Git/GitHub), students become eligible for a broad range of fresher-level software development roles. These roles include, but are not limited to: Full Stack Developer, Java Developer, MERN Stack Developer, React Developer, Backend Developer (Java/Node.js), Frontend Developer, Web Developer, Application Developer, Software Engineer, UI Developer, API Developer, Software Development Intern, Trainee Software Engineer, Junior Full Stack Engineer and Graduate Engineer Trainee (GET). |
| **Data Analytics and Data Science course** | As this course encompasses a broad curriculum including statistics, Excel, SQL, Python, Power BI, Tableau, Machine Learning, and data visualization tools, students can be placed across various fresher-level analytical and data-centric roles in IT and non-IT companies. These include, but are not limited to: Data Analyst, Business Analyst, Data Science Intern, Junior Data Scientist, MIS Analyst, Reporting Analyst, BI Developer, Research Analyst, SQL Analyst, Python Developer (Data Focused), Data Engineer - Intern, Associate Analyst, Insight Analyst, Decision Science Analyst, Analytics Executive and ML Trainee. |


• Once a student is shortlisted after final discussion or if he is offered, he can’t decline the opportunity. If declined, his placement process stands cancelled and he has to take a re-admission by paying full course fee.
• AWDIZ will not be held responsible if a candidate leaves the company voluntarily or if they are terminated by the employer due to poor performance or misbehaviour. If a candidate accepts a job offer from any company, whether self-obtained or through AWDIZ, they will not be eligible for further job placements or refunds through AWDIZ 100% job guarantee program.
• 30 Days of post-placement support will be provided to the students whose complete payment has been received and who have required percentage of attendance (85%) and mock exam assessment marks (85%) as per our policy. This support will only be extended under specific conditions, such as: Layoffs/Downsizing, Offer Revoked, Non-IT Role Offered, Unethical Conditions, Salary Not Honoured all supported by legal and official evidence.
• Post-placement support will not be extended to the candidates who have been terminated due to misconduct, behavioural issues, disciplinary action, or absconding from duty, Insufficient technical knowledge, irregular attendance, Voluntary resignation, education and experience document mismatch, unrealistic salary expectations, job stress, dissatisfaction with work culture, or unwillingness to relocate or work in rotational shifts.
• Once a candidate has availed their second job opportunity through Awdiz meeting the criteria for post placement support mentioned above, their training and placement services will be considered complete, and they will no longer be eligible to reapproach for further placements or training repetitions.
• Only after three months of completing their graduation, students pursuing regular degree courses will become eligible for the Job Guarantee programs provided by AWDIZ. If the candidate opts for further higher education, the Job Guarantee agreement will be cancelled and the student would not be eligible for training repetitions or fee refunds.

• **AWDIZ has the authority to utilize the placement information, images, and videos of the candidate for promotional and marketing purposes, regardless of whether the candidate secured placement through AWDIZ or by themselves.**
• Under no circumstances will AWDIZ refund fees or cancel the admission of students enrolled for job guaranteed master programs.
• There is a non-refundable and non-transferable policy for all our courses at AWDIZ. AWDIZ does not offer refunds for any reason after a candidate has been admitted into a course. Once the candidate pays the course fee and is admitted, he/she is committed to completing the course. It is important for the candidate to fully understand the course and the associated requirements before enrolling and making the payment. In case of any doubts or queries, the candidate should get in touch with the Admissions team for clarification before making the payment.
• Under the AWDIZ 100% Job Guaranteed Program, if students are unable to crack minimum interviews outlined in this agreement, they must be ready to accept job offers, at any location irrespective of qualification. This ensures that AWDIZ upholds its commitment to 100% Placement for all its course. 100% Job Guarantee means we will provide job interviews until placed or until minimum offer of  INR 12,000 –  INR 15,000 CTC is received. Students must accept such offers to fulfil the 100% placement guarantee clause.
• AWDIZ shall not be liable for delays or failure in job placements due to economic downturns, hiring freezes, pandemics, or external events beyond its control.
• Awdiz can make changes to the course fee, the location of its office, the teachers, course content, schedule, timings, and the start date of batches if they have good reasons. If any changes are made, Awdiz Institute will inform students within appropriate time for them to manage the training continuity.
• Students must follow the agreed payment schedule provided at the time of admission. Delays beyond the due date will lead to:
  - Immediate deactivation of LMS access, recorded lectures, test portals, and classroom/online participation.
  - If dues remain pending for more than 15 days, AWDIZ holds the right to terminate admission without any refund.
  - To resume training, students must clear all dues and pay a reactivation fee of  INR 2,000 (if applicable), subject to approval by the Center Manager.
• Students who opt for EMI (Equated Monthly Instalment) or instalment-based payment plans must make timely payments on or before each due date without fail. Any missed or bounced EMI will lead to the following consequences:
  - Immediate suspension of access to all training sessions, LMS platform, assessments, and placement-related services until dues are cleared.
  - If two or more EMIs are missed, the student will be considered a defaulter, and the entire remaining course fee becomes due immediately in one lump sum.
  - In the case of bounced EMIs or failed auto-debits, the student will be solely responsible for any legal action, penalties, late fees, or third-party recovery proceedings initiated by the financing partner or bank.
  - AWDIZ shall not be held responsible for any consequences, reputational damage, legal notices, or credit score issues that may arise due to the student’s non-payment or financial default with the EMI provider or bank.
  - Continued non-payment beyond 30 days will result in permanent cancellation of admission and job guarantee services, without refund.
• AWDIZ management team may at any time in its sole discretion change the rules set forth above as per the market demand and dynamics to stay updated. AWDIZ reserves the right to modify or change the course structure, content, and syllabus at any point in time.
• The student agrees to fully indemnify and hold harmless Awdiz Institute from and against any and all claims, losses, liabilities, damages, costs, or expenses (including reasonable legal fees) arising out of or in connection with any act, omission, misrepresentation, or breach during the training and placement duration at Awdiz by the candidate.
• Any additions, deletions, or modifications to this agreement shall communicated in writing via official email or in the official LMS App of Awdiz. Such changes shall be deemed effective immediately and should be accepted by the students. Digital acknowledgment or email / LMS confirmation will be treated as legally binding consent equivalent to physical signature.

**Note:** **Complete fee payment is mandatory to apply for interviews. Candidate with pending fees (for any reason) will strictly not be allowed for any interviews arranged by Awdiz. Center Manager approval for complete full payment needs to be submitted to placement team for initiating interviews after training.**

Kindly take admission at AWDIZ if the clauses of all the terms and conditions mentioned above are satisfying to you. Once you are admitted to our institute means you have read all our terms and conditions and you are agreeing with it.

I/We hereby declare that the information given by me on the Online/Offline Registration / Application Form etc. is correct to the best of my knowledge and belief. I/We understand that in the event of any information found to be incorrect or false, my admission may be cancelled.

I/We the Father/Mother/ or the student hereby severally and jointly declare that I / we have read and understood all the clauses contained in the Declaration on the Registration and agree to abide by them without any reservation or ambiguity and I/We have taken a print of all the terms and conditions for my future reference.

**NOTE: This contract is valid for a period of 12 Months from the date of signing the contract.**
**Any legal matter/dispute is subject to Mumbai Jurisdiction only.**

**AWDIZ Office Address 1:** 2nd Floor, Vashi Plaza Building, Office no. 421A, A Wing, Sector 17, Vashi, Navi Mumbai, Maharashtra 400703
**Awdiz Office Address 2:** Ground floor, A 791, KC Marg, next to 81 Aureate, Reclamation, Bandra West, Mumbai, Maharashtra 400050

**Note:** Kindly submit **2 Passport Size Photographs, One Digital Photograph for online records, PAN Card and Aadhar/ Driving License** photocopy along with signed copy of this agreement.
`.trim();
